[target.x86_64-unknown-linux-gnu]
pre-build = [
    # Install the cross compiler
    "apt-get update && apt-get install -y libc6 g++-x86-64-linux-gnu libc6-dev-amd64-cross gcc binutils-x86-64-linux-gnu",
]

[target.x86_64-unknown-linux-gnu.env]
# Set the linker and information for `cc` crate to link properly
passthrough = [
    "CARGO_BUILD_TARGET",
    "CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=x86_64-linux-gnu-gcc",
    "CC_x86_64_unknown_linux_gnu=x86_64-linux-gnu-gcc",
    "CXX_x86_64_unknown_linux_gnu=x86_64-linux-gnu-g++",
]

[target.x86_64-unknown-linux-gnu.image]
name = "ubuntu:20.04"
# This is the magic, if left unspecified, the default would be that the toolchain is `x86_64-unknown-linux-gnu`
toolchain = ["aarch64-unknown-linux-gnu"]