---
name: CI
on:
  pull_request:
  push:
    branches:
      - "*"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@just

      - uses: cargo-bins/cargo-binstall@main
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: clippy rustfmt

      - run: cargo binstall -y bpf-linker

      - name: Build Tamanoir
        run: just tamanoir-build

      - name: Build Tamanoir-C2
        run: |
          sudo apt install -y protobuf-compiler
          just c2-build

      - name: Build TUI
        run: just tui-build

      - name: Linting
        run: |
          cargo fmt --all -- --check
          cargo clippy -p tamanoir-ebpf  -- -D warnings
          cargo clippy --workspace --all-features --exclude tamanoir-ebpf  -- -D warnings
